//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPManager.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1,42130")]
        public string Server
        {
            get
            {
                return ((string)(this["Server"]));
            }
            set
            {
                this["Server"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NPDataNorWay")]
        public string Database
        {
            get
            {
                return ((string)(this["Database"]));
            }
            set
            {
                this["Database"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string UserID
        {
            get
            {
                return ((string)(this["UserID"]));
            }
            set
            {
                this["UserID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nexpa1234")]
        public string Password
        {
            get
            {
                return ((string)(this["Password"]));
            }
            set
            {
                this["Password"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string ParkCode
        {
            get
            {
                return ((string)(this["ParkCode"]));
            }
            set
            {
                this["ParkCode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ConnectionTimeout
        {
            get
            {
                return ((int)(this["ConnectionTimeout"]));
            }
            set
            {
                this["ConnectionTimeout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CommandTimeout
        {
            get
            {
                return ((int)(this["CommandTimeout"]));
            }
            set
            {
                this["CommandTimeout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05")]
        public string DevCode
        {
            get
            {
                return ((string)(this["DevCode"]));
            }
            set
            {
                this["DevCode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("센터")]
        public string DevName
        {
            get
            {
                return ((string)(this["DevName"]));
            }
            set
            {
                this["DevName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool INData_Save
        {
            get
            {
                return ((bool)(this["INData_Save"]));
            }
            set
            {
                this["INData_Save"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OUTData_Save
        {
            get
            {
                return ((bool)(this["OUTData_Save"]));
            }
            set
            {
                this["OUTData_Save"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MAX_LIST
        {
            get
            {
                return ((int)(this["MAX_LIST"]));
            }
            set
            {
                this["MAX_LIST"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int AP_Port
        {
            get
            {
                return ((int)(this["AP_Port"]));
            }
            set
            {
                this["AP_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public string GUESTDISCOUNT
        {
            get
            {
                return ((string)(this["GUESTDISCOUNT"]));
            }
            set
            {
                this["GUESTDISCOUNT"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Beep
        {
            get
            {
                return ((string)(this["Beep"]));
            }
            set
            {
                this["Beep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YES")]
        public string ViewLinkLabel
        {
            get
            {
                return ((string)(this["ViewLinkLabel"]));
            }
            set
            {
                this["ViewLinkLabel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full")]
        public string CheckInReg
        {
            get
            {
                return ((string)(this["CheckInReg"]));
            }
            set
            {
                this["CheckInReg"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full")]
        public string CheckOutReg
        {
            get
            {
                return ((string)(this["CheckOutReg"]));
            }
            set
            {
                this["CheckOutReg"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3:")]
        public string PrtSetting
        {
            get
            {
                return ((string)(this["PrtSetting"]));
            }
            set
            {
                this["PrtSetting"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2012-01-01 12:00:00")]
        public string RptInDate
        {
            get
            {
                return ((string)(this["RptInDate"]));
            }
            set
            {
                this["RptInDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2013-01-01 08:20:14")]
        public string RptOutDate
        {
            get
            {
                return ((string)(this["RptOutDate"]));
            }
            set
            {
                this["RptOutDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01더1234")]
        public string RptCarNumber
        {
            get
            {
                return ((string)(this["RptCarNumber"]));
            }
            set
            {
                this["RptCarNumber"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124")]
        public int RptParkTime
        {
            get
            {
                return ((int)(this["RptParkTime"]));
            }
            set
            {
                this["RptParkTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RptParkMoney
        {
            get
            {
                return ((int)(this["RptParkMoney"]));
            }
            set
            {
                this["RptParkMoney"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int RptReceiveMoney
        {
            get
            {
                return ((int)(this["RptReceiveMoney"]));
            }
            set
            {
                this["RptReceiveMoney"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RptDiscountContent
        {
            get
            {
                return ((string)(this["RptDiscountContent"]));
            }
            set
            {
                this["RptDiscountContent"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int RptDiscountMoney
        {
            get
            {
                return ((int)(this["RptDiscountMoney"]));
            }
            set
            {
                this["RptDiscountMoney"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Max_Lpr
        {
            get
            {
                return ((int)(this["Max_Lpr"]));
            }
            set
            {
                this["Max_Lpr"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.66.31")]
        public string CenterBoothIP
        {
            get
            {
                return ((string)(this["CenterBoothIP"]));
            }
            set
            {
                this["CenterBoothIP"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DongHo
        {
            get
            {
                return ((bool)(this["DongHo"]));
            }
            set
            {
                this["DongHo"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsManager
        {
            get
            {
                return ((bool)(this["IsManager"]));
            }
            set
            {
                this["IsManager"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAlarm
        {
            get
            {
                return ((bool)(this["UseAlarm"]));
            }
            set
            {
                this["UseAlarm"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAlarmSound
        {
            get
            {
                return ((bool)(this["UseAlarmSound"]));
            }
            set
            {
                this["UseAlarmSound"] = value;
            }
        }
    }
}
